### ISSUE TITLE
Export Scale - NaN

### ISSUE THREAD

**Issue by agnither** [DragonBones/DesignPanel#15]
DataFormat: dataJson
TextureFormat: texturePng
Can't set float export scale, it automatically sets to NaN, exporting x1 texture

**Comment by akdcl** [comment]
Thanks, the bug has been fixed in dev branch

**Comment by BenoitFreslon** [comment]
Hello @akdcl could you please export the DragonBonesDesignPanel.zxp with this fix?

Thanks.

EDIT: Actually I also got this issue in the textfield "Blending time(sec)"

**Comment by akdcl** [comment]
Hello @BenoitFreslon, please check below.
https://github.com/DragonBones/DesignPanel/blob/dev/DragonBonesDesignPanel.zxp

**Comment by ghost** [comment]
Hi!
I checkout dev branch and this issue still exist. When the "Export Scale" input is changed, value equal NaN

**Comment by BenoitFreslon** [comment]
Still bugging :(

Import > Blending time > 0.1 > NaN
![img](http://i.imgur.com/yW0dKLa.png)

Behavior list > Blending Time (sec): 0.1 > 0
![img](http://i.imgur.com/hfak7tw.png)

Export > Export Scale > 0.5 > NaN
![img](http://i.imgur.com/Xxfqym4.png)
